[[Greetings]]
message = "buonanotte"
from_hour = 0
to_hour = 6

[[Greetings]]
message = "buongiorno"
from_hour = 6
to_hour = 12

[[Greetings]]
message = "buon pomeriggio"
from_hour = 12
to_hour = 18

[[Greetings]]
message = "buona sera"
from_hour = 18
to_hour = 24
