[[Greetings]]
message = "good night"
from_hour = 0
to_hour = 6

[[Greetings]]
message = "good morning"
from_hour = 6
to_hour = 12

[[Greetings]]
message = "good afternoon"
from_hour = 12
to_hour = 18

[[Greetings]]
message = "good evening"
from_hour = 18
to_hour = 24
