[RPiServer]
port = 1234
gradients_path = ""
links_path = ""
greetings_path = ""

[WeatherService]
api_key = ""
city = ""
language = ""
cache_duration = 300

[UnsplashService]
api_key = ""
cache_duration = 30
